### ISSUE TITLE
Integration with react-css-modules

### ISSUE THREAD

**Issue by natecox** [brunch/css-brunch#11] opened 2016-09-11 05:32 UTC
Bear with me here, I'm just starting my journey to understand and use CSS modules and I'm probably missing something obvious.

I'm using a Phoenix server with Brunch + postcss to serve a React frontend, and I'd like to use CSS modules to scope styles to React components. There is a [package](https://github.com/gajus/react-css-modules) to include CSS modules into react components, and I've configured brunch as per the readme to use modules which also seems to be working.

The catch is that when I attempt to import my stylesheet into the React component with `import styles from './styles.css' I get console errors telling me that`styles.css` could not be found. 

The file is absolutely there in the file system, but I have been completely unable to import it. I also tried adding `postcss-modules` to the brunch config (though from the docs here I don't think that's actually required) and in that case I can see it generating a json file with the class mappings, but I'm still unable to import.

I have a suspicion that my include paths just aren't set up to look for stylesheets, but if that's the case I'm not sure how to go about configuring them.

Any help on this would be greatly appreciated. If there is more information that I can provide let me know what it is and I'll do so.

**Comment by goshakkk** [comment] 2016-09-12 08:05
Hi! Sorry to hear that. I'm sure this is something that can be resolved.

Can you take some time to create a small, focused application that reproduces the issue and put it in the open? This is something that makes debugging 10x, if not 100x, easier, meaning the faster resolution and everyone's happy. The [Brunch contributing guidelines](https://github.com/brunch/brunch/blob/master/CONTRIBUTING.md) explicitly mention this :)

**Comment by natecox** [comment] 2016-09-13 05:50
I've set up a bare-bones repo to demonstrate the issue: 
https://github.com/natecox/css-modules-test/tree/master/web/static

You can see my react component and the associated stylesheet in `web/static/js/components/HelloModules`, and when you run the project you should see a javascript error in the console informing you that the stylesheet could not be loaded.

**Comment by razor-x** [comment] 2016-09-20 23:35
@natecox I'm not sure if this is the same issue I just ran into, but I believe that if css-brunch runs before postcss-brunch, the module will not be exported correctly. I moved postcss-brunch above css-brunch in my `package.json` and modules are working for me.

I don't think you need to use postcss-modules in the postcss-brunch plugin config since that is exactly what css-brunch is already doing.

Of course, whenever I run `npm install` I suspect it will undo the ordering, so this is not ideal. I think what we need is for postcss-brunch to support css-modules directly so we can drop the css-brunch plugin.

**Comment by natecox** [comment] 2016-09-21 00:15
I can confirm that moving 

    "postcss-brunch": "^2.0.3",

above

    "css-brunch": "^2.6.1",

in my `package.json` solved the issue completely; however, I can also confirm that installing another package via the command line will restore the original ordering and break the modules again.

**Comment by razor-x** [comment] 2016-09-22 16:56
@natecox Have a look at my linked PR above for a better solution.

**Comment by denysdovhan** [comment] 2016-12-28 15:01
@natecox @natecox @goshakkk hey guys, is this issue still relevant? I think we can close it.

**Comment by natecox** [comment] 2016-12-28 19:50
Don't keep it open on my account; I've abandoned Brunch for Webpack due to too many implementation issues.

**Comment by denysdovhan** [comment] 2016-12-28 20:06
I that case, please, close.

**Closed** 2016-12-28 21:02 UTC
